### ISSUE TITLE
Syntax Error in update-dns-up.sh

### ISSUE THREAD

**Issue by zuwuko** [andresmazzo/linode-ddns#1]
In file update-dns-ip.sh the following line did not work for me (testing on ubuntu I was getting invalid IPv4 since it was passing the variable blank):
`"target": "$NEW_IP",`
Changing it to the following line DID work for me:
`"target": "'"$NEW_IP"'",`

**Comment by andresmazzo** [comment]
Sorry for the delay @zuwuko ! Thanks for the issue. I will fix it as soon as possible.

**Comment by andresmazzo** [comment]
Done. Better late than never :)
